### ISSUE TITLE
No Credits Given

### ISSUE THREAD

**Issue by Blade3575** [cursey/kanan#10]
Getting tired of there being no credits given. Bitmap (already give credit for it) and Elf Lag (not given credit for) were created by myself. The rest were created by Step29. If people are going to port over sharker codes, you should at least give the credits. The credits are even in the opening post for sharker.

**Comment by cursey** [comment]
Those patches were contributed by QewQew.  I've added a contribution guideline in the readme.

**Comment by Blade3575** [comment]
Thank you. Though I would like it if you would refrain from reversing any more patches from Abyss. Not quite the place to talk about the matter, but I would like this known.

**Comment by draconis-pendragon** [comment]
Contributed patches should also have a original source or concept cited.  This is out of courtesy to who actually came up with it originally--not just who supplied it.  Otherwise, it's like ripping code from someone else's program and not giving credit due--even though it's open source (which mod_sharker) is.

**Comment by cursey** [comment]
Yes, I explained that [here](https://github.com/cursey/kanan#contributing).

**Comment by draconis-pendragon** [comment]
I agree with what you're doing (Not that you need my approval lol)
Something like this may be in order:
___
Contributed by: QewQew
Original concept/patch by: Step29

this is just for as an example.

**Comment by cursey** [comment]
Okay, I'll make it even clearer.

**Comment by cursey** [comment]
I made it clearer who the original patch authors were and since all reverse engineered patterns are removed I am gonna close this issue.  If you know an author of any patch supplied by kanan please open a new issue or make a PR as described [here](https://github.com/cursey/kanan#contributing).
