### ISSUE TITLE
Kanan not functioning after most recent maintenance.

### ISSUE THREAD

**Issue by GuiltyMiller** [cursey/kanan#102]
It seems that Kanan has stopped working after the most recent maintenance(Maplestory x Mabinogi event.) and crashes upon injection. I'm not sure how to give a detailed debug report, but it seems that its unable to find patterns for some scripts?

**Comment by Aahzmandius** [comment]
It's running fine for me using latest code...
- Have you run mabi without kanan to see if it still crashes?
- Have you updated kanan in a while?
- If you're using a data folder, how is it set up? (using kanan's data folder redirect, packing, etc.)
- Is a different patcher like Abyss involved?

**Comment by GuiltyMiller** [comment]
My bad, I should've updated in the first place; but it was Kanan itself that was crashing before I updated. No other patches were involved and my data folder is set up the same way Kanan comes out of the zip.

I must've screwed up when adding scripts to mine.
