### ISSUE TITLE
Which specific script enables HP indicators above head?

### ISSUE THREAD

**Issue by truthfulie** [cursey/kanan#105]
Which specific script enables HP indicators above head?

**Comment by Aahzmandius** [comment]
It's part of ClientSideDevCat.js, gives the effects of devcat title, which include numeric HP indicators and a few other things.

**Comment by truthfulie** [comment]
Thank you for the reply.

**Comment by cursey** [comment]
Some users encounter strange bugs when using this feature so it has been disabled by default. To re-enable it remove it from `disabled.txt`.
