### ISSUE TITLE
32-bit Python Triggers NGS?

### ISSUE THREAD

**Issue by ghost** [cursey/kanan#113]
I've seen some posts about NGS triggering with kanan if you're using the 32-bit version of Python.
After some testing, this seems to be the case.
Is there any guesses as to why this would be?

Is there anyone running 32-bit Python who isn't getting NGS?
If it's true that the cause is 32-bit Python, maybe add a note or link to the 64-bit version, since it is slightly harder to find on the official Python homepage and the homepage links directly to the 32-bit version.

**Comment by cursey** [comment]
Yes NGS seems to be kicking people using the 32-bit version of Python and not the 64-bit version. I'll make a note of this in the readme but it is not a permanent fix. Once they start detecting the 64-bit version of Python I will be able to start developing proper ways of hiding kanan which will be fun :smile:
