### ISSUE TITLE
WindowsAppearFaster Crashing?

### ISSUE THREAD

**Issue by ghost** [cursey/kanan#12]
@cursey where was it crashing for you?

**Comment by cursey** [comment]
Near northern tir moongate and when teleporting to tail moongate by the druid.

**Comment by ghost** [comment]
Can't seem to replicate this. I'll test it some more later.

**Comment by Coziestest** [comment]
It crashes me when moving towards moongates also.
It isn't unheard of either:
https://mabimods.net/index.php?topic=14837.msg245001#msg245001

**Comment by ghost** [comment]
Seems to crash me now, too.

**Comment by cursey** [comment]
I fixed it.
