### ISSUE TITLE
Multiple clients using kanan

### ISSUE THREAD

**Issue by inesse13** [cursey/kanan#13]
Is there a way for it to function with/attach to more than one client at a time?

**Comment by cursey** [comment]
I can add that no problem.

**Comment by inesse13** [comment]
Wonderful, much obliged!

**Comment by cursey** [comment]
Alright kanan now supports attaching to specific instances of mabi given a process id.  Read the readme [here](https://github.com/cursey/kanan#things-to-be-aware-of) for more details.  To find the process id use a tool like [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx).

**Comment by ghost** [comment]
Reminder to close this issue. :+1:
