### ISSUE TITLE
ManaTunnelLagFix lacks a config entry

### ISSUE THREAD

**Issue by InvalidUUID** [cursey/kanan#133]
As said in the title, 
Simple omission of a script in the config.toml, should be an easy fix but I have no idea how GitHub works.

**Comment by Aahzmandius** [comment]
ManaTunnelLagFix no longer exists, so shouldn't have an entry... it was being investigated as no longer necessary, so was removed.  If you still want to use it, should be able to add the config entry yourself and everything will work fine.

**Comment by cursey** [comment]
As @Aahzmandius said, it was removed because we decided it wasn't necessary anymore. You may still have it if you have been updating kanan by simply overwriting the old files with the new ones. Deleting the script should also fix it, unless you have some reason to keep it around.
