### ISSUE TITLE
Bitmap

### ISSUE THREAD

**Issue by Blade3575** [cursey/kanan#14]
It appears as though the new patches in Bitmap were reversed from Abyss as well. I was told that there would be no more reversing from Abyss.

**Comment by cursey** [comment]
There was no further reversing since I had already reversed it.

**Comment by Blade3575** [comment]
Again, I will ask you to remove any work that was taken from mine as this constitutes intellectual theft of my property.

**Comment by cursey** [comment]
I'm not releasing any of your work.

**Comment by Blade3575** [comment]
The patch bytes are definitely my work. As well as the patch locations. All of it was taken from my work.

**Comment by Azurealistic** [comment]
@Blade3575 Lay off already.

**Comment by Blade3575** [comment]
@annabelle52 If someone took something you spent time on, made, and didn't so much as credit you by name, you wouldn't care? I beg to differ. Abyss has been being updated for years now. The only patcher to stick around as long as it has. Having someone come in and do this to my work is quite insulting. There wasn't even an attempt to as for permission, and the case continues to be so.

**Comment by cursey** [comment]
I did credit you from the very beginning.  There is no code in kanan that you have written.  There never was.

**Comment by Blade3575** [comment]
I was credited as "that guy". Kind of insulting. As far as the code, you took it and you've been using it. You may have changed the method of which you find where to patch, but the patch coding is still mine.

You reversed and used my patch code without any permission. You continue to do so now. This is the problem.

**Comment by cursey** [comment]
May I use the original code I wrote for BitmapFont.js that used the patterns I reversed from Abyss?

**Comment by Azurealistic** [comment]
@Blade3575 You may have written the logic, but as far as I know, when you decompile or reverse a dll, it doesn't give you original code, it gives assembler or something of the like. From that point of view, the code Kanan wrote is not only different, it's also a different language. I'm not sure how you can call the memory patches original property, because regardless of if they were reversed or not, memory would be in same place, correct? So end result would be the same.

**Comment by Blade3575** [comment]
@cursey You may; as long as you don't reverse any other patches from Abyss. If there is something in high demand that you want from Abyss, ask and we can try and figure something out.

@annabelle52 When you reverse, you can obtain the hex bytes used; since this is exactly what decompiling/reversing shows you. The byes used to replace, and the location were all the same, and it was admitted it was taken from Abyss. This was the problem. The problem is resolved so long as the terms are agreed to in this comment.

**Comment by Azurealistic** [comment]
@Blade3575 I'm just asking for curiosity now. But, the way I understand it, there wouldn't be other places to apply the hex bytes or such, right? That is, if @cursey figured them out on their own, the bytes would still be the same, correct?

**Comment by Blade3575** [comment]
@annabelle52 For the most part. There will always be other ways to do edits, but the most common would have been the way it was done by Abyss. Yes, that does mean none of this would have happened if they did not admit to taking it from Abyss. However, this would have brought up a lot of questions about it. I appreciate that they admitted to it. I'm sad that it came down to this, but integrity needs to be upheld when it comes to obeying the rules. If rules keep being broken, then the world would be a mess. I hope everyone understand the situation as it is now.

**Comment by Azurealistic** [comment]
@Blade3575 Okay, That makes sense.

**Comment by Blade3575** [comment]
As long as @cursey comments that she agrees to the terms here, it will be able to be up on MM again.

**Comment by draconis-pendragon** [comment]
I've verified and seen this per Blade mentions here.  I'm waiting for agreement so I can cite it in the thread.  After this I'll archive certain parts of the thread and sweep it away, to allow for a clean slate.  Many opportunities are being given--in most cases, this usually isn't the case.  Just a note for those have their opinions.  The only person I'm awaiting confirmation on now is kanan.  (Copied to the thread so you may respond there as well)

**Comment by cursey** [comment]
Sounds good to me.
