### ISSUE TITLE
Random Crashing

### ISSUE THREAD

**Issue by SoSadToday** [cursey/kanan#140]
I've been randomly crashing when I speak to an NPC, or view a cut scene, or warp somewhere. It has been doing for awhile, not sure if it's cause of downgrading to a previous frida or not. Most of the time it will do it after I speak to a couple NPC's or just stay in game for some amount of time, then when I do any of the actions stated earlier, the game will freeze then crash.

**Comment by Kyralis** [comment]
Try disabling npc fast text first. Then report back if there are any changes. I have no way to test this.

**Comment by SoSadToday** [comment]
Just tried disabling NPCFastText.js when I got home roughly an hour ago, still froze and crashed when speaking to an NPC after a certain amount of time being on.

EDIT: I turned off HideNPCCurtains.js and that seems to have fixed it.
