### ISSUE TITLE
How to use IDA to analyze Client?

### ISSUE THREAD

**Issue by kaneorotar** [cursey/kanan#142]
Hi All,

I've seen 'IDA unicode string view' mentioned several times in the comment section of a few scripts.

With the hope to find these memory locations myself, I've tried using IDA to disassemble Client.exe but got nothing because the file is packed by Themida. Attaching to the process doesn't seem to work, either.

Can anyone tell me the correct method to debug the client with IDA?

Thanks.

**Comment by ghost** [comment]
You will need to unpack the client or dump it while it's running.
See https://github.com/cursey/kanan/issues/42

**Comment by kaneorotar** [comment]
Thanks!

I thought this would be a common question but didn't check the closed issues.
