### ISSUE TITLE
CP view displays normal as "weak".

### ISSUE THREAD

**Issue by Rydian** [cursey/kanan#145]
1.0-1.4x CP enemies normally show with no tag, but the mod is tagging them as weak (as if they were 0.8x-1.0x).

**Comment by blookvoodow** [comment]
This would be nice. Is it possible to just prepend the cp to whatever is being returned by createAltNameStr? idk just a thought

**Comment by Kyralis** [comment]
You should be able to change the names fairly easily in the showcombatpower.js at the bottom.. Kanan displays weak on similar ranked enemies so they are not be skipped over by the cp numerical data display in the jmptable. Though I think there may be a way to get around that if she decides to try.
`       This should change the display name of the current names.

        Memory.writeUtf16String(weakestStr, cp.toFixed() + " <mini>CHANGEME </mini>");
        Memory.writeUtf16String(weakStr, cp.toFixed() + " <mini>CHANGEME </mini>");
        Memory.writeUtf16String(strongStr, cp.toFixed() + " <mini>STRONG </mini>");
        Memory.writeUtf16String(awfulStr, cp.toFixed() + " <mini>AWFUL </mini>");
        Memory.writeUtf16String(bossStr, cp.toFixed() + " <mini>BOSS </mini>");`

**Comment by cursey** [comment]
Ok I'll look into fixing it.

**Comment by cursey** [comment]
Give that a try and let me know if it works as intended. Was pretty fun figuring it out :smile:.

**Comment by cursey** [comment]
Closed since I'm pretty sure my last commit fixes this issue.
