### ISSUE TITLE
[Fixed]Was working on a different computer, Need help with opening kanan.

### ISSUE THREAD

**Issue by Tamelions** [cursey/kanan#152]
https://puu.sh/tqjjh/6a52f84485.png
Did the same on another computer, it worked but on this computer?
No clue.

**Comment by cursey** [comment]
Try temporarily removing/disabling AutoSetMTU.js and let me know what happens.

**Comment by Tamelions** [comment]
https://puu.sh/tqkxu/5ba2eab86a.png
Here ya go

**Comment by cursey** [comment]
Yeah, I'm getting the same issue when I use the latest version of frida. They must have changed something, I will check.

**Comment by Tamelions** [comment]
much thanks!

**Comment by cursey** [comment]
Ok, so the latest commit (d1d530c) should fix the issue you discovered. Thanks for bringing it to my attention and please give it a try by redownloading the project 😄

**Comment by Tamelions** [comment]
thank you!

**Comment by Tamelions** [comment]
Ive been wondering, What is Kanan auto start with morg? tried to run it as admin but it says im not running as admin? should i mess with it?

**Comment by ghost** [comment]
It runs Mabinogi with Kanan and Morrighan, a mabinogi packet analyzer.

**Comment by logancrow3** [comment]
so im not great with programming and what not, and having a problem with #152, how do i fix it?
https://gyazo.com/667b70c62d5a6204749fb1c92073a09b

**Comment by cursey** [comment]
Have you downloaded the latest version of the kanan files recently?

**Comment by logancrow3** [comment]
i think so, friend sent me the files last night

**Comment by cursey** [comment]
The only version of kanan supported here is directly from this Github page https://github.com/cursey/kanan (click the green 'Clone or download' button then press the 'Download ZIP' link).

**Comment by logancrow3** [comment]
ill try that

**Comment by cursey** [comment]
If you would rather use your friends version, you can fix the problem you're encountering by installing an older version of frida. Open a windows console and type `pip install frida==7.2.14`.

**Comment by logancrow3** [comment]
ok looks like its working now besides those 2 scripts ( i think their scripts lol) 
https://gyazo.com/0481803952381340e879c1f3de8111fe

**Comment by cursey** [comment]
Yep, those two need to be fixed still. Glad its working though! :smile:

**Comment by logancrow3** [comment]
turns it on for the first time- curious, is there a mod in here that makes the sky just white? and i probably shouldnt message that here lol

**Comment by cursey** [comment]
@logancrow3 `NoRenderSky.js` is the name of it.

**Comment by logancrow3** [comment]
thanks again owo;;;
