### ISSUE TITLE
[Request]Modify entity/character render distance

### ISSUE THREAD

**Issue by blookvoodow** [cursey/kanan#157]
I was wondering if it's possible to overwrite the distance at which entities begin to appear in your field of view? In a map with high numbers of players, sometimes the range at which they appear in your FoV becomes very limited even though the map has a much higher render distance. For example, when dueling someone west of Dunbarton, if you are far enough apart from one another, they could disappear from your FoV after landing a magnum.

**Comment by cursey** [comment]
Unfortunately, the server determines when you are able to see someone. When the server decides two players are close enough to view each other, the server sends the information about the other to them (this information includes what they look like, what they're wearing, what skills they currently have loaded, what direction they are facing, etc). When the server decides those two players are far enough apart to no longer be visible to one another, it sends information telling the client to stop drawing them and stops sending updates about that player.

**Comment by blookvoodow** [comment]
Ah I see, thanks for the info.
