### ISSUE TITLE
White text while using Auto Start?

### ISSUE THREAD

**Issue by Sasameku** [cursey/kanan#161]
![white text](https://cloud.githubusercontent.com/assets/22554527/24697042/484f321a-1a1e-11e7-9229-f9f019b65fdf.PNG)

When using Kanan Auto Start, the game's text becomes completely white.

**Comment by Rydian** [comment]
Are you using any data folder mods?

**Comment by cursey** [comment]
Auto start isn't working at the moment. I don't think anything kanan does would cause that white text to appear so I'm closing this issue.
