### ISSUE TITLE
Autostart not working 

### ISSUE THREAD

**Issue by ladypotato** [cursey/kanan#163]
When I open the auto start and attempt to log in it always says the account is invalid each time

**Comment by Aahzmandius** [comment]
Yes, it's a known issue, autostart will not work until we understand the token Nexon launcher passes to the client and how to generate it. For now you must start Kanan without autostart, and then launch mabi through either Steam or the Nexon launcher.

**Comment by logancrow3** [comment]
ik this isnt the place but, how to fix this?
![image](https://cloud.githubusercontent.com/assets/25257674/26279104/692ddc14-3d70-11e7-873e-18c41c1a6365.png)

**Comment by cursey** [comment]
autostart has been fixed.
