### ISSUE TITLE
Shifting/resetting idle annimations

### ISSUE THREAD

**Issue by logancrow3** [cursey/kanan#165]
i recently redownloaded this for update, and my character shifts/idle resets and its bugging me, is kanan have anything to do with that? xwx

**Comment by milktao** [comment]
nope, its affecting everyone ^^

**Comment by logancrow3** [comment]
oh, nexon needs to fix then, but itll take 6 months i bet

**Comment by cursey** [comment]
Not an issue with kanan so I am closing this issue.
