### ISSUE TITLE
"The Returned" Title Harvesting Skills Glitch

### ISSUE THREAD

**Issue by Raeffion** [cursey/kanan#166]
Whenever I have this title equipped, any harvesting skills such as herbalism or egg gathering never end. I have had no problem with any other skills. I asked around just in case it was Nexon's mistake but no one else had this issue so I am assuming it would be Kanan (which I could be wrong, it might just be other conflicting mods).

**Comment by Aahzmandius** [comment]
This is a known possible side-effect of the devcat debug mod. It only causes these kinds of problems for about 3/10 people, and usually infrequently. Disable it in your config.toml and check if that fixes your problem.
```
[ClientSideDevCat]
enable = false
```

**Comment by Raeffion** [comment]
That solved it, but I am a little sad that I can't keep it on, it's quite useful. Hopefully a better fix can be found soon.

**Comment by cursey** [comment]
This is a side-effect of the ClientSideDevCat script so I am closing this issue.
