### ISSUE TITLE
FOV script not working?

### ISSUE THREAD

**Issue by Jevak** [cursey/kanan#170]
all the scripts seem to be working fine but I didn't notice any difference in the FOV with the fovchange script, so to test it out, i set the FOV in the script all the way down to 50, to try and see a big difference, and no change. Is the script broken?

Edit: So it turns out there is a difference that i didn't even notice it was so small, my FOV is now set to 0 in the script, and I would have to guess that the setting were as follows

180(default) = about 40 degree fov
120 = about 65 degree fov
90 = about 75 degree fov
40 = about 90 degree fov
0 = about 100 degree fov

and "quake pro mlg airhorn" should be more like 110-120 degrees imo witch I guess would be unachiveable, but the whole quake fov was always way too fisheye for me.

But anyway, i just wanting to give the mod devs a heads up, maybe it's just on my end that the setting seem to be a bit weird?

**Comment by cursey** [comment]
I'm glad the script is still working for you. And thanks for revising your post so that I can close the issue. :smile:
