### ISSUE TITLE
Attaching kanan to steam client

### ISSUE THREAD

**Issue by LukasTD** [cursey/kanan#175]
For some reason I cannot attach kanan to a steam mabi client, it always gives me this error : http://i.imgur.com/gZLhKQb.png. 
Furthermore, if I have a steam client up, and open a nexon launcher client, I cannot attach kanan to it, I have to close all steam clients in order to attach kanan to the nexon launcher client.

**Comment by cursey** [comment]
I've just released a fixed version of kanan auto start.bat that lets you easily multi-client. I've never tested kanan with the steam version so if someone else has information about that it would be great.

**Comment by LukasTD** [comment]
you're a god
