### ISSUE TITLE
unable to run .bat

### ISSUE THREAD

**Issue by tsruht** [cursey/kanan#18]
whenever i run the bat file as admin command prompt quickly opens and closes on my screen doing nothing to the client

**Comment by cursey** [comment]
When you type `python --version` into a command prompt what does it output?  Also, can you open an administrator command prompt, `cd` to the directory you have kanan extracted to and type 

```
python kanan.py --debug
```

and paste the output here.

**Comment by tsruht** [comment]
python --version  displays

Python 3.5.2

this is what i get when i go to my kanan dir with admin cmd and use python kanan.py --debug

Traceback (most recent call last):
  File "kanan.py", line 1, in <module>
    import frida
ImportError: No module named 'frida'

**Comment by cursey** [comment]
Thats strange, the bat file should have installed frida on the first run.  Install firda by typing

```
pip install frida
```

into a console.

**Comment by tsruht** [comment]
when i try to use `pip install frida` i get this

'pip' is not recognized as an internal or external command,
operable program or batch file.

could i have done something wrong when i was installing python?

**Comment by cursey** [comment]
You may have, `pip` should have been installed along with python.  Have you rebooted your computer since you installed python?

**Comment by tsruht** [comment]
yes ive also resintalled python once

edit: it use worked about 2 days ago then i hadnt used tried to use it until today

**Comment by cursey** [comment]
Well, `pip` should be installed with python 3.5 by default, and it seems like you did check the box that says **Add Python to PATH** when installing.  Make sure no other versions of python are installed.  As a workaround, you can use the following to hopefully fix it.

```
python -m pip install frida
```

Or...

```
cd %USERPROFILE%\AppData\Local\Programs\Python\Python35\Scripts
pip install frida
```

From a command prompt.

**Comment by tsruht** [comment]
i figured it out when i installed it the first time i put it in a directory i didnt want it in and when i uninstalled it and then reinstalled it it did not completely uninstall it from first location so i just moved those files to the new directory and it worked

would have never notcied if i did not see Scripts as a directory for python in your post thank you for your help
