### ISSUE TITLE
Unable to load DLL

### ISSUE THREAD

**Issue by Forgivinegar** [cursey/kanan#27]
While all the rest of the javascript files in Kanan seem to work perfectly fine, the patches from Abyss.dll or mod_sharker don't seem to apply for me. Strangely, despite the command prompt saying they've been loaded and an Abyss_patchlog.txt and mod_sharker.log being created, there is no combat power, increased zoom, CC to same channel, gold commas, infinite party time, or anything at all in effect.

Here's what everything looks like:

https://imgur.com/a/zktmo

(Windows 7 Ultimate 64bit)

Is there something I'm doing wrong?

**Comment by cursey** [comment]
Put the configs for abyss/sharker in the mabi folder.

**Comment by Forgivinegar** [comment]
That worked, thank you!
