### ISSUE TITLE
Missing Scripts

### ISSUE THREAD

**Issue by michael5323** [cursey/kanan#31]
The following scripts seem to be missing in the repository
EvGAutoRevive.js
RemoveSunglare.js

**Comment by cursey** [comment]
Yeah, I'm keeping EvgAutoRevive.js private for now because of how it works.  RemoveSunglare.js was reversed from Abyss and I don't have permission to release any more scripts that I reversed from Abyss unfortunately.

See [this issue](https://github.com/cursey/kanan/issues/14) for more detail.

**Comment by michael5323** [comment]
Will EvgAutoRevive.js ever be available to the public?

**Comment by michael5323** [comment]
Just one more question I'd like to ask will EvgAutoRevive.js ever be released or was that apart of abyss?

**Comment by cursey** [comment]
It's a script I wrote prior to making kanan public, it's not part of Abyss.  As for making it public, maybe.
