### ISSUE TITLE
Continuous Attachment

### ISSUE THREAD

**Issue by ghost** [cursey/kanan#38]
Is it possible to add a switch for "continuous attachment", that is, even after attaching to one client, it will continue to look for any newly launched clients to attach and patch?
I'm testing some things and this requires me to repeatedly close and open clients, and I don't want to keep having to launch kanan for each time I launch a client.

Thanks :)

**Comment by cursey** [comment]
This will only rerun the scripts on new instances of mabi if all previous instances are closed.  Is this what you wanted?

**Comment by ghost** [comment]
I was thinking of attaching to all new instances as they are launched without having to close others, but this works just as well, since I won't be multi-clienting. Thanks! :+1:

**Comment by cursey** [comment]
Yeah I plan on improving multi-client support soon!
