### ISSUE TITLE
Remove Similar Chat Message Block / Rate Limiting

### ISSUE THREAD

**Issue by ghost** [cursey/kanan#41]
Could we get a patch that removes:
- Skipped repeated messages for network stability.
- You cannot enter multiple messages so quickly. Please wait a moment and try again.

Thanks <3

**Comment by Blade3575** [comment]
This would just end up being used for bots and to make it easier to annoy people. I feel as though this is a patch that shouldn't be public.. though kind of already is at this point.. Just my opinion though.

**Comment by Kyralis** [comment]
I agree to the repeated messages thing when you re-type what you said previously but have to put something in between or reword it. But the other part I disagree with. You should not be able to type enough lines to make that message appear quick enough unless you are not using full sentences, in which case why would you not if you have that much to say.
Talking
Like
this
Makes
No
sense.

**Comment by inklit** [comment]
@Kyralis I don't think it's possible to remove one or the other. They both must be removed at once.

**Comment by cursey** [comment]
So I've gone ahead and added `ChatAllowSameMsg.js` but have not pushed `ChatNoRateLimit.js` which I also wrote.  I think there should be discussion on the pros/cons of releasing it since it can lead to more spam.

**Comment by Kyralis** [comment]
@inklit
I believe in her skills.

**Comment by ghost** [comment]
Considering "ClientSideDevCat" patch bypasses these, which is already included in kanan, I don't see why not.
I just don't want to have to use the devcat title.

**Comment by cursey** [comment]
Oh I didn't realize ClientSideDevCat did that already.

**Comment by Poshwosh** [comment]
Allowing bots to spam faster would make no difference, people will chat in their own chat or black list them, same as before.

I think that as long as issue (suggestion) #44 gets resolved, it should be fine. Competent people would just filter out gold sellers with it.

What else does DevCat patch do QewQew? I didn't realize it does it as well.

**Comment by cursey** [comment]
@Rydian has improved `ClientSideDevCat.js` so I've decided to release `ChatNoRateLimit.js` because its redundant now. I plan on making a normal chat filter similar to the party market chat filter as well.
