### ISSUE TITLE
Always Day/Night

### ISSUE THREAD

**Issue by ghost** [cursey/kanan#45]
Could we possibly get a script for always day/night mod? :)

**Comment by Poshwosh** [comment]
Modifying the values should be easy, but the question is how will this be turned on and off on the fly in-game. Kanan doesn't have any functionality like that yet.

Could make some useful switches with it, day/night, fps, default ranged skill, cutscene skip when grinding the same dungeon, maybe even a first person view mod.

**Comment by Rydian** [comment]
Does anybody here know what the day/night/time values are kept as anyways?  Scanning for all value types is annoying, waiting for the passage of time and not being sure at which point it resets.
