### ISSUE TITLE
ShowCombatPower stops calculating new CP

### ISSUE THREAD

**Issue by Poshwosh** [cursey/kanan#48]
This bug occurred twice now but I never understood how its caused so I haven't reported it yet, till now, since I couldn't figure out how to trigger.

After a while the script discontinues to update the Combat Power of players and they all stick to the same value. Not just their own, but a duplicate of another. Suddenly I have 3900 CP, she has 3900 CP, etc.

**Comment by blookvoodow** [comment]
Are you sure you didn't detach kanan from mabi? I had this happen to me when I'm multi-clienting and unload the wrong cmd on accident.

**Comment by Poshwosh** [comment]
Is that it then? I'm overcautious so I close down the bat file after a successful injection. I'll keep it open now.

**Comment by cursey** [comment]
`ShowCombatPower.js` is an active feature not just a patch. It works by intercepting the function that gets called to generate the alt-text for players and enemies. If you close kanan it will unload that script, which removes the interception of that function and makes it no longer work.
