### ISSUE TITLE
RemoveScreenShake.js still shakes a little bit

### ISSUE THREAD

**Issue by Poshwosh** [cursey/kanan#50]
The concept of RemoveScreenShake is based upon Abyss' disable shake feature, but it feels incomplete in comparison, there is still a small shake to be felt, it's coming from the function that uses blur.xml.

For reference I'm testing this with fireballs, there is still that shake-y blur every fireball. 

I have modified the values on blur.xml to stop it but it feels unethical to include that as a fix, so I placed it as an issue.

**Comment by cursey** [comment]
Well, screen shake and screen blur are two different things. I can look at removing screen blur separately.

**Comment by Rydian** [comment]
Disable Full Scene Effect in the in-game options.  As far as I know that's only used for screen blur and the upside-down effect that only like two enemies in the entire game can cause and I think they're part of generation quests anyways.

**Comment by cursey** [comment]
Oh, that would explain why I'm not seeing it. I'm gonna close this issue since @Rydian has addressed it. Thanks!

**Comment by Poshwosh** [comment]
I disabled it and the blur is now gone, thank you Rydian. I never realized this option does that.
