### ISSUE TITLE
Request : Money string

### ISSUE THREAD

**Issue by ghost** [cursey/kanan#55]
Hello, first of all I'd like to thank you so much for this memory patcher. I've only started using it for a week and I'm enjoying it so far but one thing I feel that is really missing is the Money string. I was wondering if this is even possible to add? Because I swear to god, I have poor eye sight and I can't even tell if it's 1m or 10m or whatever and I always have to get up really close to the screen just to check. xD 

Thanks again!

**Comment by maybecryptic** [comment]
This. With this feature, kanan can finally replace Abyss :^)
