### ISSUE TITLE
Disable Alt+Enter

### ISSUE THREAD

**Issue by ghost** [cursey/kanan#61]
Can we get a patch that disables the Alt+Enter hotkey or just straight up disable full-screen?

**Comment by ghost** [comment]
Bump. I hate accidentally pressing alt+enter and having it ruin the borderless full screen and reset my pixel density... 😭

**Comment by Poshwosh** [comment]
I tested @Rydian's script, it works as intended. You can close to the issue now @QewQew / @cursey.
