### ISSUE TITLE
Mod_Sharker/Cheat Engine Option

### ISSUE THREAD

**Issue by ChibiChoko** [cursey/kanan#7]
Would it be possible to add the option to use these patches with mod_sharker or cheat engine? I tried my hand at porting them myself but had little luck. They should have the same functionality and you can inject sharker using cheat engine.

**Comment by ghost** [comment]
Post the patches and I'll port them.

**Comment by ChibiChoko** [comment]
Well I meant the bitmap font, but I managed to port them to sharker myself once I figured out how your scripts worked.

Here is the ports

BitmapFont=1               //Original from Blade3575, ported by Kanan
[BitmapFont]
[Redacted until Blade3575 gives the okay]

**Comment by ghost** [comment]
Oh, you mean from kanan to sharker?
I ported NPCFastText from sharker, so that should already exist. As for BitmapFont, you'd need permission from Blade, since that's where it was reversed from.

**Comment by draconis-pendragon** [comment]
Per our discussions so far, the Staff of mabimods.net and Blade want anything Abyss related removed.  I see that it was converted to mod_sharker, but being this was originally pulled from Abyss.  I'd say Blade still needs to give his blessing on this.  It's not uncommon for there to be mod_sharker versions and Abyss to have similar features.

**Comment by draconis-pendragon** [comment]
Per this: https://github.com/cursey/kanan/issues/11
Blade's response at the bottom, and our chat:
[1:37:48 PM] Blade3575: Yeah
[1:38:17 PM] Blade3575: If someone had managed to figure it out on their own, from open source projects, I wouldn't have cared

On this basis the answer is no.  I'd suggest that you find an alternative source.  They are out there, or come up with your own please.

**Comment by cursey** [comment]
Closed since this isn't related to kanan.
