### ISSUE TITLE
FreezTimeOfDay. HELP!

### ISSUE THREAD

**Issue by Theoneyouknow** [cursey/kanan#76]
Hello, I am having an issue with FreezeTimeOfDay, I want the time of day to be Around the night time so (10:00 pm) but I am having trouble editing.

**Comment by ghost** [comment]
What kind of trouble are you having editing it?

The instructions are right in the script:

```
// Set this to your desired time of day (any number, from 0 to 24 will work, 
// including decimal values so if you want 7:35 to be your time of day, just
// set it to 7.35).
```

Basically, convert 10 pm to 24-hour format as a decimal.

**Comment by Poshwosh** [comment]
In which case, you would set the variable to `var desiredTimeOfDay = 22.0;`.

**Comment by Theoneyouknow** [comment]
That is all I would do? My goodness, Im such an idiot! So sorry
I had a feeling it would be that simple, I overthought about it

**Comment by cursey** [comment]
@Poshwosh I think 10pm is 22 :smile:

**Comment by Poshwosh** [comment]
Hurr I totally didn't just wake up. Edited it.

**Comment by cursey** [comment]
I think my explanation of 7:35 being 7.35 is wrong anyway. It's close enough though (7.35 is 7:21)...
