### ISSUE TITLE
Meteor Glitching

### ISSUE THREAD

**Issue by Kyralis** [cursey/kanan#77]
I don't know if it is an occurrence  related to the mod or not but ever since I updated yesterday and started to use the client launcher batch I have had some strange glitches with any meteor that is cast, it shows the moment of impact when the meteor hits the ground, and the meteor just freezes in this instance emitting its explosive effect in a stand still glowing ball of light emanating from it that engulfs the entire map. An audio loop of static plays when standing near it. Thought my headset was damaged at first or some audio bug occurred when I awoke to the sound, but then i found a meteor sitting on top of my dead character. I have not restarted my client yet to see if it resolves this however. Just posting here to see if anyone else has this issue, I will restart the game in a bit and test it again. I have all ready sent a video recording of it to kana.

**Comment by Poshwosh** [comment]
I'll report back in a bit with a test. Do you remember where exactly you had this occur?

**Comment by cursey** [comment]
I've seen this happen yesterday too.

**Comment by Poshwosh** [comment]
We are talking about the player skill Meteor Strike right?
Do you two remember specifics of how it happened, I have tried this myself just then and it seemed just fine.

**Comment by cursey** [comment]
Heres a screenie from the video.
![applicationframehost_2016-09-09_13-27-46](https://cloud.githubusercontent.com/assets/5798459/18401813/43b6c672-7691-11e6-9747-a9aa93810958.jpg)

It just sits there making lots of noise and light.

**Comment by Poshwosh** [comment]
Coolddown reset, so I had another go with default scripts on.

It's `DisableScreenFlash.js`, need to disable or delete the script for the time being @cursey, this is very unstable.

To be fair, at the time this edit was done by Step29, Meteor Strike did not exist, I didn't realize the script would affect it.

**Comment by Kyralis** [comment]
Changing channels does not resolve it, it stays with you on all channels - logging out only makes it disappear.

**Comment by cursey** [comment]
I've disabled it for now.

**Comment by Poshwosh** [comment]
Took long, but I managed to fix it. Note that I have only tested this with 2 meteor strikes. Please provide confirmation if you can @Kyralis.
