### ISSUE TITLE
issue with kanan

### ISSUE THREAD

**Issue by Aylmao101** [cursey/kanan#9]
so whenever i launch my mabi client as soon as i launch the bat file it changes the font then immediately stops responding, any fix for this?

**Comment by Rilas** [comment]
Did you try running the debug mode? It seemed to work for me.

**Comment by Aylmao101** [comment]
err not really sure how to do that

**Comment by Rilas** [comment]
Just run it as admin while the game is running. The same way you would with the regular one.

**Comment by cursey** [comment]
Try opening an administrator command prompt and running `python kanan.py` and leave it running.

**Comment by Aylmao101** [comment]
running with debug fixed it, thanks
